### ISSUE TITLE
Light node can't check balance.

### ISSUE THREAD

**Issue by esrever10** [zack-bitcoin/amoveo#48] opened 2018-01-02 04:59 UTC
When I click the [check balance] button, the page no response, below is error messages.

<img width="1248" alt="balance_error" src="https://user-images.githubusercontent.com/1320907/34474640-c25ffb9c-efbc-11e7-97ab-5a6f18fa126b.png">

**Comment by Zwilla** [comment] 2018-01-02 05:42
which browser are u using?

**Comment by esrever10** [comment] 2018-01-02 05:46
64bit Chrome 
Version: 63.0.3239.84

**Comment by zack-bitcoin** [comment] 2018-01-02 05:54
Thank you for mentioning this problem. It is fixed now.

I fixed it earlier today, but I forgot to install the new version to the server.
I installed it and tested it now.

**Closed by zack-bitcoin** 2018-01-02 05:54 UTC

**Comment by esrever10** [comment] 2018-01-02 07:47
<img width="1251" alt="balance_error2" src="https://user-images.githubusercontent.com/1320907/34477207-15515ee8-efd3-11e7-8c45-004362d47613.png">
Now I click [check balance] button, it has another error like the above screenshots.
The variable [child] sometimes be the string not the string array. This make a crash in method [link_hash].

```
function link_hash(l) {
        var h = [];
        for (var i = 1; i < l.length; i++) {
            //console.log(link[i]);
            var x = string_to_array(atob(l[i]));
            h = x.concat(h);
        }
        return hash(h);
    }
```

**Comment by lurenpa** [comment] 2018-01-03 03:11
[146.185.142.103-1514947570958.log](https://github.com/zack-bitcoin/amoveo/files/1599321/146.185.142.103-1514947570958.log)

**Comment by zack-bitcoin** [comment] 2018-01-03 03:19
I ran some tests just now, and I am unable to reproduce any error.
I also did a major update of the light node's software just now. 
I am avoiding global variables now, so I might have fixed the problem without ever seeing the problem happen.
So maybe it is fixed already.

**Comment by zack-bitcoin** [comment] 2018-01-03 03:20
I reproduced the error.
This is what happens if you are using a private key that doesn't have any money.
use the [get key from file] button to load a private key that has funds.

**Comment by esrever10** [comment] 2018-01-03 03:29
Ok. I use the amoveo-c-miner to mining now, I want to check balance in light node to know how much money I get. May be the miner get nothing now.
